<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_6xmkYBpDEey_Wfpuv-ZzVQ" name="Proceso reparto corporativo" author="davidricardopardogonzalez" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_6xmkYRpDEey_Wfpuv-ZzVQ" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_6xmkYhpDEey_Wfpuv-ZzVQ" name="Empleado (lane) " actor="_6xmkexpDEey_Wfpuv-ZzVQ">
        <elements xmi:type="process:StartEvent" xmi:id="_6xmkYxpDEey_Wfpuv-ZzVQ" name="Inicio1" outgoing="_6xmkeBpDEey_Wfpuv-ZzVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6xmkZBpDEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6xmkZRpDEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6xmkZhpDEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_qV_4IBpEEey_Wfpuv-ZzVQ" name="Esperar Fecha recoleccion" outgoing="_2d8uIBpUEey_Wfpuv-ZzVQ" incoming="_qWEJkBpEEey_Wfpuv-ZzVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qWAfMRpEEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qWAfMBpEEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qWAfMhpEEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_sneLgBpEEey_Wfpuv-ZzVQ" name="newScript()" content="import java.text.SimpleDateFormat;&#xD;&#xA;&#xD;&#xA;SimpleDateFormat formatter=new SimpleDateFormat(&quot;yyyy/MM/dd HH:mm:ss&quot;);&#xD;&#xA;Date date1=formatter.parse(fechaRecoleccion);&#xD;&#xA;return date1;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
            <referencedElements xmi:type="process:Data" xmi:id="_v0rRQBqaEeybAeFtRtWGQw" name="fechaRecoleccion" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ"/>
          </condition>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4c4gABpUEey_Wfpuv-ZzVQ" name="Recolectar y Planificar paquetes" outgoing="_6_AegBpUEey_Wfpuv-ZzVQ" incoming="_2d8uIBpUEey_Wfpuv-ZzVQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2d31oRpUEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2d31oBpUEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2d31ohpUEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2d31oxpUEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2d31pBpUEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2d31pRpUEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2d31pxpUEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2d31phpUEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4c4gChpUEey_Wfpuv-ZzVQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_QKCL0BqXEeybAeFtRtWGQw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4c4gCRpUEey_Wfpuv-ZzVQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4c4gDBpUEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateThrowMessageEvent" xmi:id="_DOTbMBpVEey_Wfpuv-ZzVQ" name="Mensaje1" outgoing="_t3te0BpZEey_Wfpuv-ZzVQ" incoming="_6_AegBpUEey_Wfpuv-ZzVQ" outgoingMessages="_krDe0BpVEey_Wfpuv-ZzVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6-80IRpUEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6-80IBpUEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6-80IhpUEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_iProkBpVEey_Wfpuv-ZzVQ" name="solicitar transporte">
            <correlation xmi:type="process:Correlation" xmi:id="_iProkRpVEey_Wfpuv-ZzVQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_iProkhpVEey_Wfpuv-ZzVQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_kq_NYBpVEey_Wfpuv-ZzVQ" name="Transporte" content="Transporte"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_krC3wBpVEey_Wfpuv-ZzVQ" name="Inicio transporte" content="Inicio transporte"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_iProlRpVEey_Wfpuv-ZzVQ"/>
          </events>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_S7yrIBp-EeybAeFtRtWGQw" name="Proceso de Reparto Nacional para clientes corporativos" outgoing="_qWEJkBpEEey_Wfpuv-ZzVQ" incoming="_6xmkeBpDEey_Wfpuv-ZzVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6xmkaBpDEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6xmkaRpDEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6xmkahpDEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_Nhog0BqEEeybAeFtRtWGQw" name="variableRegla" dataType="_6xmkkBpDEey_Wfpuv-ZzVQ">
            <defaultValue xmi:type="expression:Expression" xmi:id="_Nhog0RqEEeybAeFtRtWGQw" content="" returnType="java.lang.Double"/>
          </data>
          <data xmi:type="process:Data" xmi:id="_US-RwBqEEeybAeFtRtWGQw" name="reglaRecogida" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ">
            <defaultValue xmi:type="expression:Expression" xmi:id="_US-RwRqEEeybAeFtRtWGQw" content=""/>
          </data>
          <connectors xmi:type="process:Connector" xmi:id="_gvoRoBqCEeybAeFtRtWGQw" name="reglaValidarHorario" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_gvoRoRqCEeybAeFtRtWGQw" definitionId="rest-post" version="1.1.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRohqCEeybAeFtRtWGQw" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRoxqCEeybAeFtRtWGQw" name="https://enviaprod-5npw2wutna-ue.a.run.app/webservice/REST/EnviaProyect/EnviaProyect/HorariosRecoleccion" content="https://enviaprod-5npw2wutna-ue.a.run.app/webservice/REST/EnviaProyect/EnviaProyect/HorariosRecoleccion" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRpBqCEeybAeFtRtWGQw" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRpRqCEeybAeFtRtWGQw" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRphqCEeybAeFtRtWGQw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRpxqCEeybAeFtRtWGQw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRqBqCEeybAeFtRtWGQw" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_gvoRqRqCEeybAeFtRtWGQw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRqhqCEeybAeFtRtWGQw" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_gvoRqxqCEeybAeFtRtWGQw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRrBqCEeybAeFtRtWGQw" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRrRqCEeybAeFtRtWGQw" name="&lt;pattern-expression>" content="{&#xD;&#xA;&quot;cliente&quot;: &quot;${solicitud.cliente}&quot;&#xD;&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_6BrHMBqOEeybAeFtRtWGQw" name="solicitud.cliente" content="solicitud.cliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_6BrHMRqOEeybAeFtRtWGQw" name="solicitud" content="solicitud" type="TYPE_VARIABLE" returnType="com.company.model.BusinessObject">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6BrHMhqOEeybAeFtRtWGQw" name="solicitud" dataType="_6xmklBpDEey_Wfpuv-ZzVQ" className="com.company.model.BusinessObject"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRrhqCEeybAeFtRtWGQw" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRrxqCEeybAeFtRtWGQw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRsBqCEeybAeFtRtWGQw" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRsRqCEeybAeFtRtWGQw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRshqCEeybAeFtRtWGQw" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRsxqCEeybAeFtRtWGQw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRtBqCEeybAeFtRtWGQw" key="trust_self_signed_certificate">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRtRqCEeybAeFtRtWGQw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRthqCEeybAeFtRtWGQw" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRtxqCEeybAeFtRtWGQw" name="Strict" content="Strict" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRuBqCEeybAeFtRtWGQw" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRuRqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRuhqCEeybAeFtRtWGQw" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRuxqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRvBqCEeybAeFtRtWGQw" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRvRqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRvhqCEeybAeFtRtWGQw" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRvxqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRwBqCEeybAeFtRtWGQw" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRwRqCEeybAeFtRtWGQw" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRwhqCEeybAeFtRtWGQw" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRwxqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRxBqCEeybAeFtRtWGQw" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRxRqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRxhqCEeybAeFtRtWGQw" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRxxqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRyBqCEeybAeFtRtWGQw" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRyRqCEeybAeFtRtWGQw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRyhqCEeybAeFtRtWGQw" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRyxqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRzBqCEeybAeFtRtWGQw" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRzRqCEeybAeFtRtWGQw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoRzhqCEeybAeFtRtWGQw" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_gvoRzxqCEeybAeFtRtWGQw" name="HTTPS" content="HTTPS" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoR0BqCEeybAeFtRtWGQw" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_gvoR0RqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoR0hqCEeybAeFtRtWGQw" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_gvoR0xqCEeybAeFtRtWGQw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoR1BqCEeybAeFtRtWGQw" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_gvoR1RqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoR1hqCEeybAeFtRtWGQw" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_gvoR1xqCEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoR2BqCEeybAeFtRtWGQw" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_gvoR2RqCEeybAeFtRtWGQw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gvoR2hqCEeybAeFtRtWGQw" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_gvoR2xqCEeybAeFtRtWGQw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_gvoR3BqCEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gvoR3RqCEeybAeFtRtWGQw" name="reglaPickup" content="reglaPickup" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_v15ecBqIEeybAeFtRtWGQw" name="reglaPickup" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gvoR3hqCEeybAeFtRtWGQw" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_gvoR3xqCEeybAeFtRtWGQw" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gvoR4BqCEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gvoR4RqCEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gvoR4hqCEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gvoR4xqCEeybAeFtRtWGQw" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_gvoR5BqCEeybAeFtRtWGQw" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gvoR5RqCEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gvoR5hqCEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gvoR5xqCEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gvoR6BqCEeybAeFtRtWGQw" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_gvoR6RqCEeybAeFtRtWGQw" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gvoR6hqCEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gvoR6xqCEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gvoR7BqCEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gvoR7RqCEeybAeFtRtWGQw" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_gvoR7hqCEeybAeFtRtWGQw" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gvoR7xqCEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gvoR8BqCEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gvoR8RqCEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gvoR8hqCEeybAeFtRtWGQw" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_gvoR8xqCEeybAeFtRtWGQw" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gvoR9BqCEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_7R15IBqPEeybAeFtRtWGQw" name="sorFechaRecoleccion" definitionId="rest-post" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_7R15IRqPEeybAeFtRtWGQw" definitionId="rest-post" version="1.1.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15IhqPEeybAeFtRtWGQw" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_7R15IxqPEeybAeFtRtWGQw" name="https://vehiculemanager.oceams.co/api/SchedulePickup" content="https://vehiculemanager.oceams.co/api/SchedulePickup" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15JBqPEeybAeFtRtWGQw" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_7R15JRqPEeybAeFtRtWGQw" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15JhqPEeybAeFtRtWGQw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_7R15JxqPEeybAeFtRtWGQw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15KBqPEeybAeFtRtWGQw" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_7R15KRqPEeybAeFtRtWGQw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15KhqPEeybAeFtRtWGQw" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_7R15KxqPEeybAeFtRtWGQw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15LBqPEeybAeFtRtWGQw" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_7R15LRqPEeybAeFtRtWGQw" name="&lt;pattern-expression>" content="{&#xD;&#xA;&quot;value&quot;: ${reglaPickup}&#xD;&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_GntlMBqQEeybAeFtRtWGQw" name="reglaPickup" content="reglaPickup" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_GntlMRqQEeybAeFtRtWGQw" name="reglaPickup" content="reglaPickup" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_GntlMhqQEeybAeFtRtWGQw" name="reglaPickup" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15LxqPEeybAeFtRtWGQw" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_7R15MBqPEeybAeFtRtWGQw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15MRqPEeybAeFtRtWGQw" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_7R15MhqPEeybAeFtRtWGQw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15MxqPEeybAeFtRtWGQw" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_7R15NBqPEeybAeFtRtWGQw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15NRqPEeybAeFtRtWGQw" key="trust_self_signed_certificate">
                <expression xmi:type="expression:Expression" xmi:id="_7R15NhqPEeybAeFtRtWGQw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15NxqPEeybAeFtRtWGQw" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_7R15OBqPEeybAeFtRtWGQw" name="Strict" content="Strict" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15ORqPEeybAeFtRtWGQw" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_7R15OhqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15OxqPEeybAeFtRtWGQw" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_7R15PBqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15PRqPEeybAeFtRtWGQw" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_7R15PhqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15PxqPEeybAeFtRtWGQw" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_7R15QBqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15QRqPEeybAeFtRtWGQw" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_7R15QhqPEeybAeFtRtWGQw" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15QxqPEeybAeFtRtWGQw" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_7R15RBqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15RRqPEeybAeFtRtWGQw" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_7R15RhqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15RxqPEeybAeFtRtWGQw" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_7R15SBqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15SRqPEeybAeFtRtWGQw" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_7R15ShqPEeybAeFtRtWGQw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15SxqPEeybAeFtRtWGQw" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_7R15TBqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15TRqPEeybAeFtRtWGQw" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_7R15ThqPEeybAeFtRtWGQw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15TxqPEeybAeFtRtWGQw" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_7R15UBqPEeybAeFtRtWGQw" name="HTTPS" content="HTTPS" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15URqPEeybAeFtRtWGQw" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_7R15UhqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15UxqPEeybAeFtRtWGQw" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_7R15VBqPEeybAeFtRtWGQw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15VRqPEeybAeFtRtWGQw" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_7R15VhqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15VxqPEeybAeFtRtWGQw" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_7R15WBqPEeybAeFtRtWGQw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15WRqPEeybAeFtRtWGQw" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_7R15WhqPEeybAeFtRtWGQw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7R15WxqPEeybAeFtRtWGQw" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_7R15XBqPEeybAeFtRtWGQw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_7R15XRqPEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_7R15XhqPEeybAeFtRtWGQw" name="fechaRecoleccion" content="fechaRecoleccion" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_ttuoUBqZEeybAeFtRtWGQw" name="fechaRecoleccion" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_7R15XxqPEeybAeFtRtWGQw" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_7R15YBqPEeybAeFtRtWGQw" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7R15YRqPEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_7R15YhqPEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_7R15YxqPEeybAeFtRtWGQw" name="" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_7R15ZBqPEeybAeFtRtWGQw" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_7R15ZRqPEeybAeFtRtWGQw" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7R15ZhqPEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_7R15ZxqPEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_7R15aBqPEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_7R15aRqPEeybAeFtRtWGQw" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_7R15ahqPEeybAeFtRtWGQw" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7R15axqPEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_7R15bBqPEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_7R15bRqPEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_7R15bhqPEeybAeFtRtWGQw" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_7R15bxqPEeybAeFtRtWGQw" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7R15cBqPEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_7R15cRqPEeybAeFtRtWGQw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_7R15chqPEeybAeFtRtWGQw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_7R15cxqPEeybAeFtRtWGQw" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_7R15dBqPEeybAeFtRtWGQw" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7R15dRqPEeybAeFtRtWGQw" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_oswCYBpEEey_Wfpuv-ZzVQ" name="Confirmar fecha recoleccion" definitionId="email" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_oswCYRpEEey_Wfpuv-ZzVQ" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCYhpEEey_Wfpuv-ZzVQ" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_oswCYxpEEey_Wfpuv-ZzVQ" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCZBpEEey_Wfpuv-ZzVQ" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_oswCZRpEEey_Wfpuv-ZzVQ" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCZhpEEey_Wfpuv-ZzVQ" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_oswCZxpEEey_Wfpuv-ZzVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCaBpEEey_Wfpuv-ZzVQ" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_oswCaRpEEey_Wfpuv-ZzVQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCahpEEey_Wfpuv-ZzVQ" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_oswCaxpEEey_Wfpuv-ZzVQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCbBpEEey_Wfpuv-ZzVQ" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_oswCbRpEEey_Wfpuv-ZzVQ" name="oachicapro@gmail.com" content="oachicapro@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCbhpEEey_Wfpuv-ZzVQ" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_oswCbxpEEey_Wfpuv-ZzVQ" name="wxxdfovognehfpiv" content="wxxdfovognehfpiv" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCcBpEEey_Wfpuv-ZzVQ" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_oswCcRpEEey_Wfpuv-ZzVQ" name="david970828@gmail.com" content="david970828@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCchpEEey_Wfpuv-ZzVQ" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_oswCcxpEEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCdBpEEey_Wfpuv-ZzVQ" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_oswCdRpEEey_Wfpuv-ZzVQ" name="david970828@gmail.com" content="david970828@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCdhpEEey_Wfpuv-ZzVQ" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_oswCdxpEEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCeBpEEey_Wfpuv-ZzVQ" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_oswCeRpEEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCehpEEey_Wfpuv-ZzVQ" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_oswCexpEEey_Wfpuv-ZzVQ" name="Fecha recoleccion" content="Fecha recoleccion" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCfBpEEey_Wfpuv-ZzVQ" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_oswCfRpEEey_Wfpuv-ZzVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCfhpEEey_Wfpuv-ZzVQ" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_oswCfxpEEey_Wfpuv-ZzVQ" name="newScript()" content="fechaRecoleccion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_0OxTcBqZEeybAeFtRtWGQw" name="fechaRecoleccion" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCgBpEEey_Wfpuv-ZzVQ" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_oswCgRpEEey_Wfpuv-ZzVQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswCghpEEey_Wfpuv-ZzVQ" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_oswCgxpEEey_Wfpuv-ZzVQ" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswChBpEEey_Wfpuv-ZzVQ" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_oswChRpEEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oswChhpEEey_Wfpuv-ZzVQ" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_oswChxpEEey_Wfpuv-ZzVQ"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6xmkaxpDEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6xmkbBpDEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6xmkbRpDEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6xmkbhpDEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6xmkbxpDEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_-wGxkBpUEey_Wfpuv-ZzVQ" name="Senda1">
        <elements xmi:type="process:IntermediateCatchSignalEvent" xmi:id="_t3k78BpZEey_Wfpuv-ZzVQ" name="Señal1" signalCode="llegadaVehiculo" outgoing="_NPNk0BpoEey_Wfpuv-ZzVQ" incoming="_t3te0BpZEey_Wfpuv-ZzVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t3nYMRpZEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t3nYMBpZEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t3nYMhpZEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_PuN94BpoEey_Wfpuv-ZzVQ" name="Descargue y Planificar paquetes origen" incoming="_NPNk0BpoEey_Wfpuv-ZzVQ" type="SEQUENTIAL" collectionDataToMultiInstantiate="_tTupwBriEey_Wfpuv-ZzVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PuN94hpoEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PuN94RpoEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PuN94xpoEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_vFsa0BrbEey_Wfpuv-ZzVQ" name="Listar todas las guias de la solicitud" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_vFsa0RrbEey_Wfpuv-ZzVQ" definitionId="rest-get" version="1.1.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa0hrbEey_Wfpuv-ZzVQ" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa0xrbEey_Wfpuv-ZzVQ" name="https://envia-corporate.herokuapp.com/api/distribution?idSolicitud=163" content="https://envia-corporate.herokuapp.com/api/distribution?idSolicitud=163" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa1BrbEey_Wfpuv-ZzVQ" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_vFsa1RrbEey_Wfpuv-ZzVQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa1hrbEey_Wfpuv-ZzVQ" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_vFsa1xrbEey_Wfpuv-ZzVQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa2BrbEey_Wfpuv-ZzVQ" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa2RrbEey_Wfpuv-ZzVQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa2hrbEey_Wfpuv-ZzVQ" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa2xrbEey_Wfpuv-ZzVQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa3BrbEey_Wfpuv-ZzVQ" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa3RrbEey_Wfpuv-ZzVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa3hrbEey_Wfpuv-ZzVQ" key="trust_self_signed_certificate">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa3xrbEey_Wfpuv-ZzVQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa4BrbEey_Wfpuv-ZzVQ" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa4RrbEey_Wfpuv-ZzVQ" name="Strict" content="Strict" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa4hrbEey_Wfpuv-ZzVQ" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa4xrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa5BrbEey_Wfpuv-ZzVQ" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa5RrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa5hrbEey_Wfpuv-ZzVQ" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa5xrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa6BrbEey_Wfpuv-ZzVQ" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa6RrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa6hrbEey_Wfpuv-ZzVQ" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa6xrbEey_Wfpuv-ZzVQ" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa7BrbEey_Wfpuv-ZzVQ" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa7RrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa7hrbEey_Wfpuv-ZzVQ" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa7xrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa8BrbEey_Wfpuv-ZzVQ" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa8RrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa8hrbEey_Wfpuv-ZzVQ" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa8xrbEey_Wfpuv-ZzVQ" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa9BrbEey_Wfpuv-ZzVQ" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa9RrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa9hrbEey_Wfpuv-ZzVQ" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa9xrbEey_Wfpuv-ZzVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa-BrbEey_Wfpuv-ZzVQ" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa-RrbEey_Wfpuv-ZzVQ" name="HTTPS" content="HTTPS" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa-hrbEey_Wfpuv-ZzVQ" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa-xrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa_BrbEey_Wfpuv-ZzVQ" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa_RrbEey_Wfpuv-ZzVQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsa_hrbEey_Wfpuv-ZzVQ" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_vFsa_xrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsbABrbEey_Wfpuv-ZzVQ" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_vFsbARrbEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsbAhrbEey_Wfpuv-ZzVQ" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_vFsbAxrbEey_Wfpuv-ZzVQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vFsbBBrbEey_Wfpuv-ZzVQ" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_vFsbBRrbEey_Wfpuv-ZzVQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_vFsbBhrbEey_Wfpuv-ZzVQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_vFsbBxrbEey_Wfpuv-ZzVQ" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_vFsbCBrbEey_Wfpuv-ZzVQ" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_vFsbCRrbEey_Wfpuv-ZzVQ" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_vFsbChrbEey_Wfpuv-ZzVQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_vFsbCxrbEey_Wfpuv-ZzVQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_vFsbDBrbEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_yQ014BriEey_Wfpuv-ZzVQ" name="multiInstanceIterator" dataType="_6xmklBpDEey_Wfpuv-ZzVQ" className="com.company.model.Guias"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_vFsbDRrbEey_Wfpuv-ZzVQ" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_vFsbDhrbEey_Wfpuv-ZzVQ" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_vFsbDxrbEey_Wfpuv-ZzVQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_vFsbEBrbEey_Wfpuv-ZzVQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_vFsbERrbEey_Wfpuv-ZzVQ" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_vFsbEhrbEey_Wfpuv-ZzVQ" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_vFsbExrbEey_Wfpuv-ZzVQ" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_vFsbFBrbEey_Wfpuv-ZzVQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_vFsbFRrbEey_Wfpuv-ZzVQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_vFsbFhrbEey_Wfpuv-ZzVQ" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_vFsbFxrbEey_Wfpuv-ZzVQ" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_vFsbGBrbEey_Wfpuv-ZzVQ" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_vFsbGRrbEey_Wfpuv-ZzVQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_vFsbGhrbEey_Wfpuv-ZzVQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_vFsbGxrbEey_Wfpuv-ZzVQ" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_vFsbHBrbEey_Wfpuv-ZzVQ" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_vFsbHRrbEey_Wfpuv-ZzVQ" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_vFsbHhrbEey_Wfpuv-ZzVQ" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PuN95hpoEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PuN95xpoEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PuN96BpoEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PuN96hpoEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.company.model.Guias" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PuN96RpoEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_PuOk8RpoEey_Wfpuv-ZzVQ" name="Descargue y Planificar paquetes origen" content="Descargue y Planificar paquetes origen" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_PuN95RpoEey_Wfpuv-ZzVQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_T5lmkBpyEeybAeFtRtWGQw" name="solicitud" dataType="_6xmklBpDEey_Wfpuv-ZzVQ" className="com.company.model.BusinessObject">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Nr0NBRqDEeybAeFtRtWGQw" name="initSolicitud()" content="def businessObjectVar = new com.company.model.BusinessObject()&#xD;&#xA;businessObjectVar.fecha_recoleccion = solicitudInput?.fecha_recoleccion&#xD;&#xA;businessObjectVar.idSolicitud = solicitudInput?.idSolicitud&#xD;&#xA;businessObjectVar.cliente = solicitudInput?.cliente&#xD;&#xA;businessObjectVar.horaLimite = solicitudInput?.horaLimite&#xD;&#xA;return businessObjectVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.BusinessObject">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Nr0NBhqDEeybAeFtRtWGQw" name="solicitudInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_FLVAYBqIEeybAeFtRtWGQw" name="reglaPickup" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_FLVAYRqIEeybAeFtRtWGQw" name="18" content="18"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_lFrNYBqZEeybAeFtRtWGQw" name="fechaRecoleccion" dataType="_6xmkkRpDEey_Wfpuv-ZzVQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_lFrNYRqZEeybAeFtRtWGQw" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_tTupwBriEey_Wfpuv-ZzVQ" name="guias" multiple="true" dataType="_6xmklBpDEey_Wfpuv-ZzVQ" className="com.company.model.Guias">
        <defaultValue xmi:type="expression:Expression" xmi:id="_tTupwRriEey_Wfpuv-ZzVQ" name="init_guias()" content="guiasDAO.newInstance()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
          <referencedElements xmi:type="expression:Expression" xmi:id="_tTupwhriEey_Wfpuv-ZzVQ" name="guiasDAO" content="guiasDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.GuiasDAO" returnTypeFixed="true"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_6xmkdBpDEey_Wfpuv-ZzVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_QKCL0RqXEeybAeFtRtWGQw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_6xmkdhpDEey_Wfpuv-ZzVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_6xmkdxpDEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6xmkeBpDEey_Wfpuv-ZzVQ" target="_S7yrIBp-EeybAeFtRtWGQw" source="_6xmkYxpDEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6xmkeRpDEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6xmkehpDEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qWEJkBpEEey_Wfpuv-ZzVQ" target="_qV_4IBpEEey_Wfpuv-ZzVQ" source="_S7yrIBp-EeybAeFtRtWGQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qWEJkRpEEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qWEJkhpEEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2d8uIBpUEey_Wfpuv-ZzVQ" target="_4c4gABpUEey_Wfpuv-ZzVQ" source="_qV_4IBpEEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2d8uIRpUEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2d8uIhpUEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6_AegBpUEey_Wfpuv-ZzVQ" target="_DOTbMBpVEey_Wfpuv-ZzVQ" source="_4c4gABpUEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6_AegRpUEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6_AeghpUEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t3te0BpZEey_Wfpuv-ZzVQ" target="_t3k78BpZEey_Wfpuv-ZzVQ" source="_DOTbMBpVEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t3te0RpZEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_t3te0hpZEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NPNk0BpoEey_Wfpuv-ZzVQ" target="_PuN94BpoEey_Wfpuv-ZzVQ" source="_t3k78BpZEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NPOL4BpoEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_NPOL4RpoEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_6xmkexpDEey_Wfpuv-ZzVQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Recoleccion" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_6xmkfBpDEey_Wfpuv-ZzVQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_Nr0NABqDEeybAeFtRtWGQw" name="solicitudInput" type="COMPLEX" dataReference="solicitud">
          <inputs xmi:type="process:ContractInput" xmi:id="_Nr0NARqDEeybAeFtRtWGQw" name="fecha_recoleccion" type="DATE"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Nr0NAhqDEeybAeFtRtWGQw" name="idSolicitud" type="INTEGER"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Nr0NAxqDEeybAeFtRtWGQw" name="cliente"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Nr0NBBqDEeybAeFtRtWGQw" name="horaLimite" type="DECIMAL"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6xmkfRpDEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_6xmkfhpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6xmkfxpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6xmkgBpDEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_6xmkgRpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6xmkghpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6xmkgxpDEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_6xmkhBpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6xmkhRpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6xmkhhpDEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_6xmkhxpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6xmkiBpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6xmkiRpDEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_6xmkihpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6xmkixpDEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_Jv0ncBpVEey_Wfpuv-ZzVQ" name="Transporte">
      <elements xmi:type="process:StartMessageEvent" xmi:id="_S93EUBpVEey_Wfpuv-ZzVQ" name="Inicio transporte" outgoing="_VFCzQBpVEey_Wfpuv-ZzVQ" event="solicitar transporte" incomingMessag="_krDe0BpVEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_NPyuQhpVEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_NPyuQRpVEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_NPyuQxpVEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_XIIFUBpVEey_Wfpuv-ZzVQ" name="Transportar paquetes" outgoing="_iG6RoBpWEey_Wfpuv-ZzVQ" incoming="_VFCzQBpVEey_Wfpuv-ZzVQ" actor="_Ze2FEBpVEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_VE-h0hpVEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_VE-h0RpVEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_VE-h0xpVEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_VE-h1BpVEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_VE-h1RpVEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VE-h1hpVEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_VE-h2BpVEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_VE-h1xpVEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_XIIsaRpVEey_Wfpuv-ZzVQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_QN2U0BqXEeybAeFtRtWGQw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_XIIsaBpVEey_Wfpuv-ZzVQ"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_XIIsaxpVEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_ip7fIBpWEey_Wfpuv-ZzVQ" name="Tarea1" outgoing="_jsUwQBpWEey_Wfpuv-ZzVQ" incoming="_ip_wkBpWEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ip8GMBpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ip7fIRpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ip8GMRpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ip8GMhpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ip8GMxpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ip8GNBpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ip8GNhpWEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ip8GNRpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndSignalEvent" xmi:id="_jsSUABpWEey_Wfpuv-ZzVQ" name="Termina proceso transporte" signalCode="llegadaVehiculo" incoming="_jsUwQBpWEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_jsS7ERpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_jsS7EBpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_jsS7EhpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_l_fswBpWEey_Wfpuv-ZzVQ" name="¿Hay novedad?" outgoing="_ip_wkBpWEey_Wfpuv-ZzVQ _ohaP4BpWEey_Wfpuv-ZzVQ" incoming="_iG6RoBpWEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_iG2nQRpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_iG2nQBpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_iG2nQhpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_ohUwUBpWEey_Wfpuv-ZzVQ" name="Tarea2" incoming="_ohaP4BpWEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ohVXYRpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ohVXYBpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ohVXYhpWEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ohVXYxpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ohVXZBpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ohVXZRpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ohVXZxpWEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ohVXZhpWEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Jv1OjxpVEey_Wfpuv-ZzVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_QN2U0RqXEeybAeFtRtWGQw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Jv1OkRpVEey_Wfpuv-ZzVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_Jv1OkhpVEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VFCzQBpVEey_Wfpuv-ZzVQ" target="_XIIFUBpVEey_Wfpuv-ZzVQ" source="_S93EUBpVEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VFCzQRpVEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_VFCzQhpVEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iG6RoBpWEey_Wfpuv-ZzVQ" target="_l_fswBpWEey_Wfpuv-ZzVQ" source="_XIIFUBpVEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iG64sBpWEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_iG64sRpWEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ip_wkBpWEey_Wfpuv-ZzVQ" name="NO" target="_ip7fIBpWEey_Wfpuv-ZzVQ" source="_l_fswBpWEey_Wfpuv-ZzVQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ip_wkRpWEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ip_wkhpWEey_Wfpuv-ZzVQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jsUwQBpWEey_Wfpuv-ZzVQ" target="_jsSUABpWEey_Wfpuv-ZzVQ" source="_ip7fIBpWEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jsUwQRpWEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jsUwQhpWEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ohaP4BpWEey_Wfpuv-ZzVQ" name="SI" target="_ohUwUBpWEey_Wfpuv-ZzVQ" source="_l_fswBpWEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ohd6QBpWEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ohd6QRpWEey_Wfpuv-ZzVQ" name="true" content="true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Ze2FEBpVEey_Wfpuv-ZzVQ" name="Transporte"/>
      <contract xmi:type="process:Contract" xmi:id="_Jv1OkxpVEey_Wfpuv-ZzVQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jv1OgBpVEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_Jv1OgRpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jv1OghpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jv1OgxpVEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_Jv1OhBpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jv1OhRpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jv1OhhpVEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_Jv1OhxpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jv1OiBpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jv1OiRpVEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_Jv1OihpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jv1OixpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Jv1OjBpVEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_Jv1OjRpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Jv1OjhpVEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_PuLhoBpoEey_Wfpuv-ZzVQ" name="Descargue y Planificar paquetes origen">
      <elements xmi:type="process:StartEvent" xmi:id="_5GN70BqfEey_Wfpuv-ZzVQ" name="Inicio subproceso" outgoing="_59aCgBqfEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_5GQYERqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_5GQYEBqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_5GQYEhqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_HghCMBqgEey_Wfpuv-ZzVQ" name="Novedad en paquete" incoming="_HgkskBqgEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_HghpQBqgEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_HghCMRqgEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_HghpQRqgEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_KhvXgBqgEey_Wfpuv-ZzVQ" name="Continua flujo" incoming="_Khya0BqgEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_KhvXghqgEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_KhvXgRqgEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_KhvXgxqgEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_Pb_rABqgEey_Wfpuv-ZzVQ" name="Reportar en SIGMA" outgoing="_HgkskBqgEey_Wfpuv-ZzVQ" incoming="_64GwMBqfEey_Wfpuv-ZzVQ" actor="_frNEkBqgEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_64ET8hqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_64ET8RqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_64ET8xqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_64ET9BqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_64ET9RqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_64ET9hqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_64ET-BqfEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_64ET9xqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_Pb_rChqgEey_Wfpuv-ZzVQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_Pb_rCxqgEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_Pb_rCRqgEey_Wfpuv-ZzVQ"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_Pb_rDBqgEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_VPVioBqgEey_Wfpuv-ZzVQ" name="Enviar a tina de ruta" outgoing="_Khya0BqgEey_Wfpuv-ZzVQ" incoming="_7Zyg8BqfEey_Wfpuv-ZzVQ" actor="_frNEkBqgEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_7ZwEsRqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_7ZwEsBqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_7ZwEshqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_7ZwEsxqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_7ZwEtBqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7ZwEtRqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_7ZwEtxqfEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_7ZwEthqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_VPViqhqgEey_Wfpuv-ZzVQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_VPWJsBqgEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_VPViqRqgEey_Wfpuv-ZzVQ"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_VPWJsRqgEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_Z9i-MBqgEey_Wfpuv-ZzVQ" name="Descargar paquetes" outgoing="_6gHuABqfEey_Wfpuv-ZzVQ" incoming="_59aCgBqfEey_Wfpuv-ZzVQ" actor="_frNEkBqgEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_59VxEhqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_59VxERqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_59VxExqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_59VxFBqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_59VxFRqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_59VxFhqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_59VxGBqfEey_Wfpuv-ZzVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_59VxFxqfEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_Z9jlSRqgEey_Wfpuv-ZzVQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_Z9jlShqgEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_Z9jlSBqgEey_Wfpuv-ZzVQ"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_Z9jlSxqgEey_Wfpuv-ZzVQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_nv9lMBqgEey_Wfpuv-ZzVQ" name="¿Existen novedades?" outgoing="_64GwMBqfEey_Wfpuv-ZzVQ _7Zyg8BqfEey_Wfpuv-ZzVQ" incoming="_6gHuABqfEey_Wfpuv-ZzVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_6gFRwhqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_6gFRwRqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_6gFRwxqfEey_Wfpuv-ZzVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_PuMvzxpoEey_Wfpuv-ZzVQ" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_PuMv0BpoEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_PuMv0RpoEey_Wfpuv-ZzVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_PuMv0hpoEey_Wfpuv-ZzVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_59aCgBqfEey_Wfpuv-ZzVQ" target="_Z9i-MBqgEey_Wfpuv-ZzVQ" source="_5GN70BqfEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_59aCgRqfEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_59aCghqfEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6gHuABqfEey_Wfpuv-ZzVQ" target="_nv9lMBqgEey_Wfpuv-ZzVQ" source="_Z9i-MBqgEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6gHuARqfEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6gHuAhqfEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_64GwMBqfEey_Wfpuv-ZzVQ" name="SI" target="_Pb_rABqgEey_Wfpuv-ZzVQ" source="_nv9lMBqgEey_Wfpuv-ZzVQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_64GwMRqfEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_64GwMhqfEey_Wfpuv-ZzVQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7Zyg8BqfEey_Wfpuv-ZzVQ" name="NO" target="_VPVioBqgEey_Wfpuv-ZzVQ" source="_nv9lMBqgEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7Zyg8RqfEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7Zyg8hqfEey_Wfpuv-ZzVQ" name="true" content="true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HgkskBqgEey_Wfpuv-ZzVQ" target="_HghCMBqgEey_Wfpuv-ZzVQ" source="_Pb_rABqgEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HgkskRqgEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HgkskhqgEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Khya0BqgEey_Wfpuv-ZzVQ" target="_KhvXgBqgEey_Wfpuv-ZzVQ" source="_VPVioBqgEey_Wfpuv-ZzVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Khya0RqgEey_Wfpuv-ZzVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Khya0hqgEey_Wfpuv-ZzVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_frNEkBqgEey_Wfpuv-ZzVQ" name="Origen y destino"/>
      <contract xmi:type="process:Contract" xmi:id="_PuMv0xpoEey_Wfpuv-ZzVQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PuMvwBpoEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_PuMvwRpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PuMvwhpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PuMvwxpoEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_PuMvxBpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PuMvxRpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PuMvxhpoEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_PuMvxxpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PuMvyBpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PuMvyRpoEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_PuMvyhpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PuMvyxpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PuMvzBpoEey_Wfpuv-ZzVQ">
        <name xmi:type="expression:Expression" xmi:id="_PuMvzRpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PuMvzhpoEey_Wfpuv-ZzVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_6xmkjBpDEey_Wfpuv-ZzVQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_6xmkjRpDEey_Wfpuv-ZzVQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_6xmkjhpDEey_Wfpuv-ZzVQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_6xmkjxpDEey_Wfpuv-ZzVQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_6xmkkBpDEey_Wfpuv-ZzVQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_6xmkkRpDEey_Wfpuv-ZzVQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_6xmkkhpDEey_Wfpuv-ZzVQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_6xmkkxpDEey_Wfpuv-ZzVQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_6xmklBpDEey_Wfpuv-ZzVQ" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_krDe0BpVEey_Wfpuv-ZzVQ" name="solicitar transporte" target="_S93EUBpVEey_Wfpuv-ZzVQ" source="_DOTbMBpVEey_Wfpuv-ZzVQ"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_6xmklRpDEey_Wfpuv-ZzVQ" type="Process" element="_6xmkYBpDEey_Wfpuv-ZzVQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Jv11kBpVEey_Wfpuv-ZzVQ" type="2007" element="_Jv0ncBpVEey_Wfpuv-ZzVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jv11lRpVEey_Wfpuv-ZzVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Jv11lhpVEey_Wfpuv-ZzVQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_S93rYBpVEey_Wfpuv-ZzVQ" type="3012" element="_S93EUBpVEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_S93rYhpVEey_Wfpuv-ZzVQ" type="5029">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_S93rYxpVEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_S93rYRpVEey_Wfpuv-ZzVQ" x="118" y="96" width="30" height="30"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_XIIsbBpVEey_Wfpuv-ZzVQ" type="3005" element="_XIIFUBpVEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_XIJTcBpVEey_Wfpuv-ZzVQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XIIsbRpVEey_Wfpuv-ZzVQ" x="235" y="91" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ip8GNxpWEey_Wfpuv-ZzVQ" type="3027" element="_ip7fIBpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_ip8tQBpWEey_Wfpuv-ZzVQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ip8GOBpWEey_Wfpuv-ZzVQ" x="525" y="180"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_jsS7ExpWEey_Wfpuv-ZzVQ" type="3020" element="_jsSUABpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_jsS7FRpWEey_Wfpuv-ZzVQ" type="5035">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_jsS7FhpWEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jsS7FBpWEey_Wfpuv-ZzVQ" x="684" y="190"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_l_gT0xpWEey_Wfpuv-ZzVQ" type="3008" element="_l_fswBpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_l_g64BpWEey_Wfpuv-ZzVQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_l_g64RpWEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l_gT1BpWEey_Wfpuv-ZzVQ" x="434" y="97" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ohV-cBpWEey_Wfpuv-ZzVQ" type="3027" element="_ohUwUBpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_ohV-chpWEey_Wfpuv-ZzVQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ohV-cRpWEey_Wfpuv-ZzVQ" x="524" y="17"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Jv11kRpVEey_Wfpuv-ZzVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Jv11khpVEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Jv11kxpVEey_Wfpuv-ZzVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Jv11lxpVEey_Wfpuv-ZzVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jv11lBpVEey_Wfpuv-ZzVQ" width="800" height="290"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_6xmklhpDEey_Wfpuv-ZzVQ" type="2007" element="_6xmkYRpDEey_Wfpuv-ZzVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_6xmklxpDEey_Wfpuv-ZzVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_6xmkmBpDEey_Wfpuv-ZzVQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_6xmkmRpDEey_Wfpuv-ZzVQ" type="3007" element="_6xmkYhpDEey_Wfpuv-ZzVQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_6xmkmhpDEey_Wfpuv-ZzVQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6xmkmxpDEey_Wfpuv-ZzVQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_6xmknxpDEey_Wfpuv-ZzVQ" type="3002" element="_6xmkYxpDEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_6xmkoBpDEey_Wfpuv-ZzVQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6xmkoRpDEey_Wfpuv-ZzVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6xmkohpDEey_Wfpuv-ZzVQ" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qWAfMxpEEey_Wfpuv-ZzVQ" type="3017" element="_qV_4IBpEEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_qWBGQBpEEey_Wfpuv-ZzVQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qWBGQRpEEey_Wfpuv-ZzVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qWAfNBpEEey_Wfpuv-ZzVQ" x="370" y="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4c5HEBpUEey_Wfpuv-ZzVQ" type="3005" element="_4c4gABpUEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4c5HEhpUEey_Wfpuv-ZzVQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4c5HERpUEey_Wfpuv-ZzVQ" x="506" y="55" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DOUCQxpVEey_Wfpuv-ZzVQ" type="3014" element="_DOTbMBpVEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_DOUCRRpVEey_Wfpuv-ZzVQ" type="5030">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DOUCRhpVEey_Wfpuv-ZzVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DOUCRBpVEey_Wfpuv-ZzVQ" x="707" y="71" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_S8l8YBp-EeybAeFtRtWGQw" type="3027" element="_S7yrIBp-EeybAeFtRtWGQw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_S8nKgBp-EeybAeFtRtWGQw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_S8l8YRp-EeybAeFtRtWGQw" x="159" y="60" width="100" height="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6xmkoxpDEey_Wfpuv-ZzVQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6xmkpBpDEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6xmkpRpDEey_Wfpuv-ZzVQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6xmkphpDEey_Wfpuv-ZzVQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6xmkpxpDEey_Wfpuv-ZzVQ" x="44" y="10" width="889" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_-wHYoBpUEey_Wfpuv-ZzVQ" type="3007" element="_-wGxkBpUEey_Wfpuv-ZzVQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_-wHYpRpUEey_Wfpuv-ZzVQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_-wHYphpUEey_Wfpuv-ZzVQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_t3omUBpZEey_Wfpuv-ZzVQ" type="3021" element="_t3k78BpZEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_t3omUhpZEey_Wfpuv-ZzVQ" type="5036">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_t3omUxpZEey_Wfpuv-ZzVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t3omURpZEey_Wfpuv-ZzVQ" x="780" y="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PuN96xpoEey_Wfpuv-ZzVQ" type="3063" element="_PuN94BpoEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PuOk8BpoEey_Wfpuv-ZzVQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PuN97BpoEey_Wfpuv-ZzVQ" x="875" y="54" width="142" height="71"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_-wHYoRpUEey_Wfpuv-ZzVQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_-wHYohpUEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_-wHYoxpUEey_Wfpuv-ZzVQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_-wHYpxpUEey_Wfpuv-ZzVQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-wHYpBpUEey_Wfpuv-ZzVQ" x="130" y="185"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_6xmkqBpDEey_Wfpuv-ZzVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_6xmkqRpDEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_6xmkqhpDEey_Wfpuv-ZzVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_6xmkqxpDEey_Wfpuv-ZzVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6xmkrBpDEey_Wfpuv-ZzVQ" width="1315" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_PuNW0BpoEey_Wfpuv-ZzVQ" type="2007" element="_PuLhoBpoEey_Wfpuv-ZzVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_PuNW1RpoEey_Wfpuv-ZzVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_PuNW1hpoEey_Wfpuv-ZzVQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_5GRmMBqfEey_Wfpuv-ZzVQ" type="3002" element="_5GN70BqfEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_5GSNQBqfEey_Wfpuv-ZzVQ" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_5GSNQRqfEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5GRmMRqfEey_Wfpuv-ZzVQ" x="124" y="175"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_HghpQhqgEey_Wfpuv-ZzVQ" type="3062" element="_HghCMBqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_HghpRBqgEey_Wfpuv-ZzVQ" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_HghpRRqgEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HghpQxqgEey_Wfpuv-ZzVQ" x="713" y="58"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Khv-kBqgEey_Wfpuv-ZzVQ" type="3003" element="_KhvXgBqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_Khv-khqgEey_Wfpuv-ZzVQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Khv-kxqgEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Khv-kRqgEey_Wfpuv-ZzVQ" x="713" y="261"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Pb_rDRqgEey_Wfpuv-ZzVQ" type="3005" element="_Pb_rABqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_PcASEBqgEey_Wfpuv-ZzVQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pb_rDhqgEey_Wfpuv-ZzVQ" x="507" y="48" width="115" height="57"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_VPWJshqgEey_Wfpuv-ZzVQ" type="3005" element="_VPVioBqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_VPWJtBqgEey_Wfpuv-ZzVQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VPWJsxqgEey_Wfpuv-ZzVQ" x="505" y="252" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Z9jlTBqgEey_Wfpuv-ZzVQ" type="3005" element="_Z9i-MBqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Z9jlThqgEey_Wfpuv-ZzVQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Z9jlTRqgEey_Wfpuv-ZzVQ" x="235" y="167" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_nv9lNBqgEey_Wfpuv-ZzVQ" type="3008" element="_nv9lMBqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_nv9lNhqgEey_Wfpuv-ZzVQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_nv9lNxqgEey_Wfpuv-ZzVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nv9lNRqgEey_Wfpuv-ZzVQ" x="392" y="172" width="43" height="43"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_PuNW0RpoEey_Wfpuv-ZzVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_PuNW0hpoEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_PuNW0xpoEey_Wfpuv-ZzVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_PuNW1xpoEey_Wfpuv-ZzVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PuNW1BpoEey_Wfpuv-ZzVQ" width="1346" height="383"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_6xmkrRpDEey_Wfpuv-ZzVQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_6xmkrhpDEey_Wfpuv-ZzVQ" type="4001" element="_6xmkeBpDEey_Wfpuv-ZzVQ" source="_6xmknxpDEey_Wfpuv-ZzVQ" target="_S8l8YBp-EeybAeFtRtWGQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6xmkrxpDEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6xmksBpDEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6xmksRpDEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6xmkshpDEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qWEwoBpEEey_Wfpuv-ZzVQ" type="4001" element="_qWEJkBpEEey_Wfpuv-ZzVQ" source="_S8l8YBp-EeybAeFtRtWGQw" target="_qWAfMxpEEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qWEwoxpEEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qWEwpBpEEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qWEwoRpEEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qWEwohpEEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2d9VMBpUEey_Wfpuv-ZzVQ" type="4001" element="_2d8uIBpUEey_Wfpuv-ZzVQ" source="_qWAfMxpEEey_Wfpuv-ZzVQ" target="_4c5HEBpUEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2d9VMxpUEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2d9VNBpUEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2d9VMRpUEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2d9VMhpUEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6_BFkBpUEey_Wfpuv-ZzVQ" type="4001" element="_6_AegBpUEey_Wfpuv-ZzVQ" source="_4c5HEBpUEey_Wfpuv-ZzVQ" target="_DOUCQxpVEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6_BFkxpUEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6_BFlBpUEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6_BFkRpUEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6_BFkhpUEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VFDaUBpVEey_Wfpuv-ZzVQ" type="4001" element="_VFCzQBpVEey_Wfpuv-ZzVQ" source="_S93rYBpVEey_Wfpuv-ZzVQ" target="_XIIsbBpVEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VFDaUxpVEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VFDaVBpVEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VFDaURpVEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VFDaUhpVEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_krDe0RpVEey_Wfpuv-ZzVQ" type="4002" element="_krDe0BpVEey_Wfpuv-ZzVQ" source="_DOUCQxpVEey_Wfpuv-ZzVQ" target="_S93rYBpVEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_krDe1BpVEey_Wfpuv-ZzVQ" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_krDe1RpVEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_krDe0hpVEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_krDe0xpVEey_Wfpuv-ZzVQ" points="[-1, -15, 607, 270]$[-1, -76, 607, 209]$[-617, -76, -9, 209]$[-617, -273, -9, 12]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iG64shpWEey_Wfpuv-ZzVQ" type="4001" element="_iG6RoBpWEey_Wfpuv-ZzVQ" source="_XIIsbBpVEey_Wfpuv-ZzVQ" target="_l_gT0xpWEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iG7fwBpWEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iG7fwRpWEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iG64sxpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iG64tBpWEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ip_wkxpWEey_Wfpuv-ZzVQ" type="4001" element="_ip_wkBpWEey_Wfpuv-ZzVQ" source="_l_gT0xpWEey_Wfpuv-ZzVQ" target="_ip8GNxpWEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ip_wlhpWEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iqAXoBpWEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ip_wlBpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ip_wlRpWEey_Wfpuv-ZzVQ" points="[0, 22, -120, -65]$[0, 86, -120, -1]$[70, 86, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jsUwQxpWEey_Wfpuv-ZzVQ" type="4001" element="_jsUwQBpWEey_Wfpuv-ZzVQ" source="_ip8GNxpWEey_Wfpuv-ZzVQ" target="_jsS7ExpWEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jsUwRhpWEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jsUwRxpWEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jsUwRBpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jsUwRRpWEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ohiLsBpWEey_Wfpuv-ZzVQ" type="4001" element="_ohaP4BpWEey_Wfpuv-ZzVQ" source="_l_gT0xpWEey_Wfpuv-ZzVQ" target="_ohV-cBpWEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ohiywBpWEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ohiywRpWEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ohiLsRpWEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ohiLshpWEey_Wfpuv-ZzVQ" points="[0, -21, -119, 55]$[0, -77, -119, -1]$[69, -77, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t3uF4BpZEey_Wfpuv-ZzVQ" type="4001" element="_t3te0BpZEey_Wfpuv-ZzVQ" source="_DOUCQxpVEey_Wfpuv-ZzVQ" target="_t3omUBpZEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t3uF4xpZEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t3uF5BpZEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t3uF4RpZEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t3uF4hpZEey_Wfpuv-ZzVQ" points="[1, 14, -125, -248]$[1, 260, -125, -2]$[111, 260, -15, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NPOL4hpoEey_Wfpuv-ZzVQ" type="4001" element="_NPNk0BpoEey_Wfpuv-ZzVQ" source="_t3omUBpZEey_Wfpuv-ZzVQ" target="_PuN96xpoEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NPOy8hpoEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NPOy8xpoEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NPOy8BpoEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NPOy8RpoEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_59apkBqfEey_Wfpuv-ZzVQ" type="4001" element="_59aCgBqfEey_Wfpuv-ZzVQ" source="_5GRmMBqfEey_Wfpuv-ZzVQ" target="_Z9jlTBqgEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_59apkxqfEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_59aplBqfEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_59apkRqfEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_59apkhqfEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6gIVEBqfEey_Wfpuv-ZzVQ" type="4001" element="_6gHuABqfEey_Wfpuv-ZzVQ" source="_Z9jlTBqgEey_Wfpuv-ZzVQ" target="_nv9lNBqgEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6gIVExqfEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6gIVFBqfEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6gIVERqfEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6gIVEhqfEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_64HXQBqfEey_Wfpuv-ZzVQ" type="4001" element="_64GwMBqfEey_Wfpuv-ZzVQ" source="_nv9lNBqgEey_Wfpuv-ZzVQ" target="_Pb_rDRqgEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_64HXQxqfEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_64HXRBqfEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_64HXQRqfEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_64HXQhqfEey_Wfpuv-ZzVQ" points="[0, -21, -151, 96]$[0, -122, -151, -5]$[94, -122, -57, -5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7Zyg8xqfEey_Wfpuv-ZzVQ" type="4001" element="_7Zyg8BqfEey_Wfpuv-ZzVQ" source="_nv9lNBqgEey_Wfpuv-ZzVQ" target="_VPWJshqgEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7ZzIABqfEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7ZzIARqfEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7Zyg9BqfEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7Zyg9RqfEey_Wfpuv-ZzVQ" points="[0, 22, -139, -67]$[0, 88, -139, -1]$[79, 88, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HgkskxqgEey_Wfpuv-ZzVQ" type="4001" element="_HgkskBqgEey_Wfpuv-ZzVQ" source="_Pb_rDRqgEey_Wfpuv-ZzVQ" target="_HghpQhqgEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HgkslhqgEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HgkslxqgEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HgkslBqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HgkslRqgEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Khya0xqgEey_Wfpuv-ZzVQ" type="4001" element="_Khya0BqgEey_Wfpuv-ZzVQ" source="_VPWJshqgEey_Wfpuv-ZzVQ" target="_Khv-kBqgEey_Wfpuv-ZzVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Khya1hqgEey_Wfpuv-ZzVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Khya1xqgEey_Wfpuv-ZzVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Khya1BqgEey_Wfpuv-ZzVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Khya1RqgEey_Wfpuv-ZzVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
